apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: john_walker_333@hotmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
      - selector:
          dnsZones:
            - johnwalkers.com
        dns01:
          route53:
            region: eu-west-2
            hostedZoneID: Z009111329P1K9L0AJ7C9
