name: Helm deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    env:
      AWS_REGION: eu-west-2
      CLUSTER_NAME: eks-lab-cluster
      HELM_RELEASE: cert-manager
      NAMESPACE: cert-manager
      CHART: jetstack/cert-manager
      HELM_REPO_NAME: jetstack
      HELM_REPO_URL: https://charts.jetstack.io

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0

      - name: Add helm repo
        run: helm repo add ${{ env.HELM_REPO_NAME }} ${{ env.HELM_REPO_URL }}

      - name: Deploy Helm chart to EKS (wait for CRDs + webhook)
        run: |
          helm upgrade --install ${{ env.HELM_RELEASE }} ${{ env.CHART }} \
            --namespace ${{ env.NAMESPACE }} --create-namespace \
            -f values.yaml \
            --wait --timeout 10m
          kubectl rollout status deploy/cert-manager-webhook -n "${{ env.NAMESPACE }}" --timeout=180s

      - name: Apply ClusterIssuer(s)
        run: |
          kubectl apply -f issuer/clusterissuer-letsencrypt.yaml
          kubectl wait --for=condition=Ready clusterissuer/letsencrypt --timeout=120s || true


        
  